[package]
name = "mp3-protocol"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1", default-features = false, features = ["derive"] }
postcard = { version = "1", default-features = false }
heapless = { version = "0.9", features = ["serde"] }
