[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --probe 2e8a:000c --always-print-stacktrace --no-location --catch-hardfault --chip RP235x"

[build]
target = "thumbv8m.main-none-eabihf"

[env]
DEFMT_LOG = "info"
SSID = ""
WIRELESS_PSK = ""
MP3_SERVER = "10.0.0.30:9010"
